#code: language=ini
dist1 ansible_host=192.168.29.11
dist2 ansible_host=192.168.29.12
access1 ansible_host=192.168.29.21
access2 ansible_host=192.168.29.22
access3 ansible_host=192.168.29.23


[access]
access1
access2
access3


[distribution]
dist1
dist2

[network:children]
access
distribution

[network:vars]
ansible_user=ansible
ansible_password=password
ansible_network_os=dellemc.enterprise_sonic.sonic
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
#ansible_ssh_common_args='-o StrictHostKeyChecking=false'
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
ansible_python_interpreter=/usr/bin/python3