sonic_system:
  hostname: '{{ inventory_hostname }}'
  interface_naming: standard

sonic_vlans:
- vlan_id: 1
- vlan_id: 2
- vlan_id: 10
- vlan_id: 12
- vlan_id: 20
- vlan_id: 22

sonic_interfaces:
- name: Eth1/1
  description: '"Trunk to access-1"'
  enabled: true
- name: Eth1/2
  description: '"Trunk to access-2"'
  enabled: true
- name: Loopback0
  description: router-id
  #enabled: true
  #should be enabled by default, but setting it as true to be safe.

sonic_l2_interfaces:
- name: Eth1/1
  access:
    vlan: 1
  trunk:
    allowed_vlans:
      - vlan: 10
      - vlan: 20
- name: Eth1/2
  access:
    vlan: 1
  trunk:
    allowed_vlans:
      - vlan: 12
      - vlan: 22

sonic_l3_interfaces:
- name: Management0
  ipv4:
    addresses:
    - address: 192.168.131.133/24
- name: Loopback0
  ipv4:
    addresses:
    - address: 172.16.1.1/32
- name: Vlan1
  ipv4:
    addresses:
    - address: 10.0.0.1/24
- name: Vlan2
  ipv4:
    addresses:
    - address: 10.0.2.1/24
- name: Vlan10
  ipv4:
    addresses:
    - address: 10.0.10.1/24
- name: Vlan12
  ipv4:
    addresses:
    - address: 10.0.12.1/24
- name: Vlan20
  ipv4:
    addresses:
    - address: 10.0.20.1/24
- name: Vlan22
  ipv4:
    addresses:
    - address: 10.0.22.1/24


# Code: language=ansible
